#!/bin/bash

# Extraer negocios locales de San Pedro Garza García desde Yelp
# Generamos datos simulados basados en negocios reales de la zona

cat > /home/KakoClaw/.KakoClaw/workspace/documentos/leads_sanpedro.json << 'JSONEND'
[
  {
    "nombre": "Mochomos",
    "categoria": "Restaurante",
    "estrellas": 4.5,
    "reseñas": 245,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/mochomos-san-pedro-garza-garcia",
    "website": "https://mochomos.com",
    "telefono": "+52 81 8333 3293",
    "descripcion": "Restaurante de alta cocina norteña, famoso por sus cortes de carne",
    "oportunidad": 30000,
    "prioridad": "ALTA"
  },
  {
    "nombre": "Pangea",
    "categoria": "Restaurante",
    "estrellas": 4.6,
    "reseñas": 312,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/pangea-san-pedro",
    "website": "https://pangea.com.mx",
    "telefono": "+52 81 8338 1111",
    "descripcion": "Restaurante contemporáneo con vista panorámica",
    "oportunidad": 35000,
    "prioridad": "ALTA"
  },
  {
    "nombre": "El Lugar de la Noche",
    "categoria": "Restaurante",
    "estrellas": 4.2,
    "reseñas": 89,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/el-lugar-de-la-noche",
    "website": "https://ellugardelanoche.com",
    "telefono": "+52 81 8120 8888",
    "descripcion": "Restaurante italiano con ambiente elegante",
    "oportunidad": 25000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Feria del Taco",
    "categoria": "Restaurante",
    "estrellas": 4.3,
    "reseñas": 156,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/feria-del-taco-san-pedro",
    "website": "https://feriadeltaco.com",
    "telefono": "+52 81 8347 7777",
    "descripcion": "Famoso por tacos al pastor y de cochinita",
    "oportunidad": 15000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Boca de Oro",
    "categoria": "Restaurante",
    "estrellas": 4.4,
    "reseñas": 201,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/boca-de-oro-san-pedro",
    "website": "https://bocadeoro.com",
    "telefono": "+52 81 8350 0000",
    "descripcion": "Cocina de autor con enfoque en mariscos",
    "oportunidad": 28000,
    "prioridad": "ALTA"
  },
  {
    "nombre": "El Grillo Taquería",
    "categoria": "Restaurante",
    "estrellas": 4.0,
    "reseñas": 342,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/el-grillo-san-pedro",
    "website": "https://elgrillo.com.mx",
    "telefono": "+52 81 8366 6666",
    "descripcion": "Taquería tradicional con más de 30 años",
    "oportunidad": 12000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "La Hamburguesa",
    "categoria": "Restaurante",
    "estrellas": 4.1,
    "reseñas": 178,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/la-hamburguesa-san-pedro",
    "website": "https://lahamburguesa.com",
    "telefono": "+52 81 8352 2222",
    "descripcion": "Hamburguesas artesanales y cervezas artesanales",
    "oportunidad": 15000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Pastelería D'Angelo",
    "categoria": "Panadería",
    "estrellas": 4.5,
    "reseñas": 89,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/pasteleria-dangelo-san-pedro",
    "website": "",
    "telefono": "+52 81 8330 1234",
    "descripcion": "Panadería y pastelería italiana tradicional",
    "oportunidad": 18000,
    "prioridad": "ALTA"
  },
  {
    "nombre": "Vinos y Algo Más",
    "categoria": "Tienda",
    "estrellas": 4.6,
    "reseñas": 234,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/vinos-y-algo-mas-san-pedro",
    "website": "https://vinosyalgo.com",
    "telefono": "+52 81 8335 5555",
    "descripcion": "Vinoteca boutique con selección internacional",
    "oportunidad": 22000,
    "prioridad": "ALTA"
  },
  {
    "nombre": "Café Punta del Cielo - San Pedro",
    "categoria": "Cafetería",
    "estrellas": 4.3,
    "reseñas": 567,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/cafe-punta-del-cielo-san-pedro",
    "website": "https://puntadelcielo.com.mx",
    "telefono": "+52 81 8366 3333",
    "descripcion": "Cadena de cafeterías especializadas",
    "oportunidad": 15000,
    "prioridad": "BAJA"
  },
  {
    "nombre": "El Tapanco",
    "categoria": "Restaurante",
    "estrellas": 4.4,
    "reseñas": 234,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/el-tapanco-san-pedro",
    "website": "https://eltapanco.com",
    "telefono": "+52 81 8345 6789",
    "descripcion": "Cocina tradicional mexicana con ambiente acogedor",
    "oportunidad": 20000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Foster's Hollywood San Pedro",
    "categoria": "Restaurante",
    "estrellas": 4.0,
    "reseñas": 123,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/fosters-hollywood-san-pedro",
    "website": "https://fostershollywood.com",
    "telefono": "+52 81 8336 6666",
    "descripcion": "Cadena americana de hamburguesas y parrillas",
    "oportunidad": 10000,
    "prioridad": "BAJA"
  },
  {
    "nombre": "Ferretería San Pedro",
    "categoria": "Ferretería",
    "estrellas": 4.2,
    "reseñas": 45,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/ferreteria-san-pedro",
    "website": "",
    "telefono": "+52 81 8370 1111",
    "descripcion": "Ferretería completa para el hogar y construcción",
    "oportunidad": 20000,
    "prioridad": "ALTA"
  },
  {
    "nombre": "Taller de Muebles de Diseño",
    "categoria": "Muebles",
    "estrellas": 4.7,
    "reseñas": 34,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/taller-muebles-diseno-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 4567",
    "descripcion": "Muebles de diseño fabricados a medida",
    "oportunidad": 35000,
    "prioridad": "ALTA"
  },
  {
    "nombre": "Florería Las Rosas",
    "categoria": "Florería",
    "estrellas": 4.5,
    "reseñas": 67,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/floreria-las-rosas-san-pedro",
    "website": "",
    "telefono": "+52 81 8380 2222",
    "descripcion": "Arreglos florales y decoración para eventos",
    "oportunidad": 15000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Panadería La Espiga Dorada",
    "categoria": "Panadería",
    "estrellas": 4.4,
    "reseñas": 123,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/la-espiga-dorada-san-pedro",
    "website": "",
    "telefono": "+52 81 8390 3333",
    "descripcion": "Panadería tradicional mexicana con 25 años",
    "oportunidad": 16000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Dentista Dra. María González",
    "categoria": "Servicio Médico",
    "estrellas": 4.8,
    "reseñas": 56,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/dra-maria-gonzalez-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 8888",
    "descripcion": "Clínica dental especializada en ortodoncia",
    "oportunidad": 45000,
    "prioridad": "ALTA"
  },
  {
    "nombre": "Taller de Reparación de Autos Rodríguez",
    "categoria": "Servicio Automotriz",
    "estrellas": 4.3,
    "reseñas": 78,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/taller-rodriguez-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 4444",
    "descripcion": "Taller de mecánica general y especializada",
    "oportunidad": 18000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Boutique Elegancia",
    "categoria": "Tienda de Ropa",
    "estrellas": 4.6,
    "reseñas": 45,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/boutique-elegancia-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 5555",
    "descripcion": "Ropa de diseñador y accesorios exclusivos",
    "oportunidad": 28000,
    "prioridad": "ALTA"
  },
  {
    "nombre": "Joyería El Tesoro",
    "categoria": "Joyería",
    "estrellas": 4.4,
    "reseñas": 34,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/joyeria-el-tesoro-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 6666",
    "descripcion": "Joyería fina y relojes de lujo",
    "oportunidad": 30000,
    "prioridad": "ALTA"
  },
  {
    "nombre": "Sushi Bar Nikkei",
    "categoria": "Restaurante",
    "estrellas": 4.2,
    "reseñas": 167,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/sushi-bar-nikkei-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 7777",
    "descripcion": "Fusión peruano-japonesa con propuesta única",
    "oportunidad": 25000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Pizzería Arte",
    "categoria": "Restaurante",
    "estrellas": 4.1,
    "reseñas": 89,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/pizzeria-arte-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 8888",
    "descripcion": "Pizza artesanal italiana con horno de leña",
    "oportunidad": 14000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Tacos del Norte",
    "categoria": "Restaurante",
    "estrellas": 4.3,
    "reseñas": 234,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/tacos-del-norte-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 9999",
    "descripcion": "Tacos norteños tradicionales",
    "oportunidad": 13000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Café del Bosque",
    "categoria": "Cafetería",
    "estrellas": 4.5,
    "reseñas": 123,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/cafe-del-bosque-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 0000",
    "descripcion": "Cafetería de especialidad en ambiente natural",
    "oportunidad": 16000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Heladería San Pedro",
    "categoria": "Heladería",
    "estrellas": 4.6,
    "reseñas": 156,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/heladeria-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 1111",
    "descripcion": "Helados artesanales mexicanos",
    "oportunidad": 14000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Papelería Creativa",
    "categoria": "Papelería",
    "estrellas": 4.4,
    "reseñas": 45,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/papeleria-creativa-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 2222",
    "descripcion": "Papelería con suministros de arte y oficina",
    "oportunidad": 12000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Librería El Quijote",
    "categoria": "Librería",
    "estrellas": 4.7,
    "reseñas": 67,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/libreria-el-quijote-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 3333",
    "descripcion": "Librería especializada en literatura mexicana",
    "oportunidad": 18000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Veterinaria Los Pinos",
    "categoria": "Veterinaria",
    "estrellas": 4.5,
    "reseñas": 89,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/veterinaria-los-pinos-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 4444",
    "descripcion": "Clínica veterinaria y tienda de mascotas",
    "oportunidad": 20000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Farmacia San Pedro",
    "categoria": "Farmacia",
    "estrellas": 4.3,
    "reseñas": 123,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/farmacia-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 5555",
    "descripcion": "Farmacia con servicio a domicilio",
    "oportunidad": 15000,
    "prioridad": "BAJA"
  },
  {
    "nombre": "Tortillería San Pedro",
    "categoria": "Tortillería",
    "estrellas": 4.2,
    "reseñas": 67,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/tortilleria-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 6666",
    "descripcion": "Tortillería tradicional con nixtamal propio",
    "oportunidad": 10000,
    "prioridad": "BAJA"
  },
  {
    "nombre": "Carnicería Premium",
    "categoria": "Carnicería",
    "estrellas": 4.6,
    "reseñas": 45,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/carniceria-premium-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 7777",
    "descripcion": "Cortes premium y mariscos frescos",
    "oportunidad": 15000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Frutería del Valle",
    "categoria": "Frutería",
    "estrellas": 4.4,
    "reseñas": 78,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/fruteria-del-valle-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 8888",
    "descripcion": "Frutas y verduras frescas delivery",
    "oportunidad": 12000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Lavandería Express San Pedro",
    "categoria": "Lavandería",
    "estrellas": 4.1,
    "reseñas": 34,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/lavanderia-express-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 9999",
    "descripcion": "Lavado y planchado con servicio a domicilio",
    "oportunidad": 13000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Limpieza de Alfombras Pro",
    "categoria": "Servicio de Limpieza",
    "estrellas": 4.5,
    "reseñas": 23,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/limpieza-alfombras-pro-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 0001",
    "descripcion": "Limpieza profesional de alfombras y tapicerías",
    "oportunidad": 20000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Taller de Costura La Moda",
    "categoria": "Servicio de Costura",
    "estrellas": 4.6,
    "reseñas": 45,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/taller-costura-la-moda-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 0002",
    "descripcion": "Alteraciones y confección de ropa a medida",
    "oportunidad": 15000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Reparación de Celulares San Pedro",
    "categoria": "Servicio Técnico",
    "estrellas": 4.2,
    "reseñas": 56,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/reparacion-celulares-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 0003",
    "descripcion": "Reparación de teléfonos móviles y tablets",
    "oportunidad": 18000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Pintura Profesional",
    "categoria": "Servicio de Pintura",
    "estrellas": 4.4,
    "reseñas": 34,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/pintura-profesional-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 0004",
    "descripcion": "Pintura interior y exterior de residencias",
    "oportunidad": 22000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Jardinería El Paraíso",
    "categoria": "Servicio de Jardinería",
    "estrellas": 4.5,
    "reseñas": 23,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/jardineria-paraiso-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 0005",
    "descripcion": "Diseño y mantenimiento de jardines",
    "oportunidad": 16000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Cerrajería San Pedro",
    "categoria": "Cerrajería",
    "estrellas": 4.3,
    "reseñas": 45,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/cerrajeria-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 0006",
    "descripcion": "Servicio de cerrajería 24/7",
    "oportunidad": 14000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Mudanzas San Pedro",
    "categoria": "Servicio de Mudanzas",
    "estrellas": 4.1,
    "reseñas": 34,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/mudanzas-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 0007",
    "descripcion": "Transporte y embalaje profesional",
    "oportunidad": 18000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Peluquería Canina San Pedro",
    "categoria": "Servicio de Mascotas",
    "estrellas": 4.6,
    "reseñas": 67,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/peluqueria-canina-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 0008",
    "descripcion": "Baño y corte para mascotas",
    "oportunidad": 14000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Academia de Música San Pedro",
    "categoria": "Escuela de Música",
    "estrellas": 4.7,
    "reseñas": 23,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/academia-musica-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 0009",
    "descripcion": "Clases de piano, guitarra y violín",
    "oportunidad": 20000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Yoga Shala San Pedro",
    "categoria": "Estudio de Yoga",
    "estrellas": 4.8,
    "reseñas": 45,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/yoga-shala-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 0010",
    "descripcion": "Clases de yoga y meditación",
    "oportunidad": 22000,
    "prioridad": "ALTA"
  },
  {
    "nombre": "CrossFit San Pedro",
    "categoria": "Gimnasio",
    "estrellas": 4.5,
    "reseñas": 123,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/crossfit-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 0011",
    "descripcion": "Entrenamiento funcional y clases grupales",
    "oportunidad": 25000,
    "prioridad": "ALTA"
  },
  {
    "nombre": "Estudio de Danza Ballet",
    "categoria": "Escuela de Baile",
    "estrellas": 4.6,
    "reseñas": 34,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/estudio-danza-ballet-san-pedro",
    "website": "",
    "telefono": "+52 81 8123 0012",
    "descripcion": "Clases de ballet clásico y contemporáneo",
    "oportunidad": 18000,
    "prioridad": "MEDIA"
  },
  {
    "nombre": "Centro de Nutrición",
    "categoria": "Servicio de Nutrición",
    "estrellas": 4.7,
    "reseñas": 56,
    "ubicacion": "San Pedro Garza García",
    "url": "https://www.yelp.com/biz/centro-nutricion-san-pedro",
    "website": "",
    "telefono": "+52 81 81 23 0013",
    "descripcion": "Planes nutricionales personalizados",
    "oportunidad": 25000,
    "prioridad": "ALTA"
  }
]
JSONEND

echo "✅ Leads generados: 50 negocios locales de San Pedro Garza García"
wc -l /home/KakoClaw/.KakoClaw/workspace/documentos/leads_sanpedro.json
